### ISSUE TITLE
Installation fails with type errors OSX10.13

### ISSUE THREAD

**Issue by kiranschana** [valderman/haste-compiler#418]
Fresh install of haskell platform 8.2.2
error on "cabal install haste-compiler"
after dependencies install...
`
Downloading haste-compiler-0.4.4.4...
Configuring haste-compiler-0.4.4.4...
Failed to install haste-compiler-0.4.4.4
Build log ( /Users/user/.cabal/logs/ghc-8.2.2/haste-compiler-0.4.4.4-Hb8vrn7aglx1rspaaMV9Pf.log ):
cabal: Entering directory '/var/folders/q3/3b4cr3cn4hg8d5bj62pdk16m0000gn/T/cabal-tmp-51525/haste-compiler-0.4.4.4'
cabal: Leaving directory '/var/folders/q3/3b4cr3cn4hg8d5bj62pdk16m0000gn/T/cabal-tmp-51525/haste-compiler-0.4.4.4'
Updating documentation index
/Users/user/Library/Haskell/share/doc/x86_64-osx-ghc-8.2.2/index.html
cabal: Error: some packages failed to install:
haste-compiler-0.4.4.4-Hb8vrn7aglx1rspaaMV9Pf failed during the configure
step. The exception was:
dieVerbatim: user error (cabal: '/usr/local/bin/ghc' exited with an error:

/var/folders/q3/3b4cr3cn4hg8d5bj62pdk16m0000gn/T/cabal-tmp-51525/haste-compiler-0.4.4.4/dist/setup/setup.hs:40:51:
error:
• Couldn't match type
‘Distribution.Types.UnqualComponentName.UnqualComponentName’
with ‘[Char]’
Expected type: FilePath
Actual type: Distribution.Types.UnqualComponentName.UnqualComponentName
• In the first argument of ‘(</>)’, namely ‘exe’
In the second argument of ‘(</>)’, namely ‘exe </> exe’
In the second argument of ‘($)’, namely ‘builddir </> exe </> exe’
|
40 | exists <- doesFileExist $ builddir </> exe </> exe
| ^^^

/var/folders/q3/3b4cr3cn4hg8d5bj62pdk16m0000gn/T/cabal-tmp-51525/haste-compiler-0.4.4.4/dist/setup/setup.hs:40:59:
error:
• Couldn't match type
‘Distribution.Types.UnqualComponentName.UnqualComponentName’
with ‘[Char]’
Expected type: FilePath
Actual type: Distribution.Types.UnqualComponentName.UnqualComponentName
• In the second argument of ‘(</>)’, namely ‘exe’
In the second argument of ‘(</>)’, namely ‘exe </> exe’
In the second argument of ‘($)’, namely ‘builddir </> exe </> exe’
|
40 | exists <- doesFileExist $ builddir </> exe </> exe
| ^^^

/var/folders/q3/3b4cr3cn4hg8d5bj62pdk16m0000gn/T/cabal-tmp-51525/haste-compiler-0.4.4.4/dist/setup/setup.hs:42:42:
error:
• Couldn't match type
‘Distribution.Types.UnqualComponentName.UnqualComponentName’
with ‘[Char]’
Expected type: FilePath
Actual type: Distribution.Types.UnqualComponentName.UnqualComponentName
• In the first argument of ‘(</>)’, namely ‘exe’
In the second argument of ‘(</>)’, namely ‘exe </> exe’
In the first argument of ‘copyFile’, namely
‘(builddir </> exe </> exe)’
|
42 | then copyFile (builddir </> exe </> exe) (outdir </> "bin" </> exe)
| ^^^

/var/folders/q3/3b4cr3cn4hg8d5bj62pdk16m0000gn/T/cabal-tmp-51525/haste-compiler-0.4.4.4/dist/setup/setup.hs:42:50:
error:
• Couldn't match type
‘Distribution.Types.UnqualComponentName.UnqualComponentName’
with ‘[Char]’
Expected type: FilePath
Actual type: Distribution.Types.UnqualComponentName.UnqualComponentName
• In the second argument of ‘(</>)’, namely ‘exe’
In the second argument of ‘(</>)’, namely ‘exe </> exe’
In the first argument of ‘copyFile’, namely
‘(builddir </> exe </> exe)’
|
42 | then copyFile (builddir </> exe </> exe) (outdir </> "bin" </> exe)
| ^^^

/var/folders/q3/3b4cr3cn4hg8d5bj62pdk16m0000gn/T/cabal-tmp-51525/haste-compiler-0.4.4.4/dist/setup/setup.hs:42:77:
error:
• Couldn't match type
‘Distribution.Types.UnqualComponentName.UnqualComponentName’
with ‘[Char]’
Expected type: FilePath
Actual type: Distribution.Types.UnqualComponentName.UnqualComponentName
• In the second argument of ‘(</>)’, namely ‘exe’
In the second argument of ‘(</>)’, namely ‘"bin" </> exe’
In the second argument of ‘copyFile’, namely
‘(outdir </> "bin" </> exe)’
|
42 | then copyFile (builddir </> exe </> exe) (outdir </> "bin" </> exe)
| ^^^

/var/folders/q3/3b4cr3cn4hg8d5bj62pdk16m0000gn/T/cabal-tmp-51525/haste-compiler-0.4.4.4/dist/setup/setup.hs:43:42:
error:
• Couldn't match type
‘Distribution.Types.UnqualComponentName.UnqualComponentName’
with ‘[Char]’
Expected type: FilePath
Actual type: Distribution.Types.UnqualComponentName.UnqualComponentName
• In the first argument of ‘(</>)’, namely ‘exe’
In the second argument of ‘(</>)’, namely ‘exe </> exe <.> "exe"’
In the first argument of ‘copyFile’, namely
‘(builddir </> exe </> exe <.> "exe")’
|
43 | else copyFile (builddir </> exe </> exe <.> "exe")
| ^^^

/var/folders/q3/3b4cr3cn4hg8d5bj62pdk16m0000gn/T/cabal-tmp-51525/haste-compiler-0.4.4.4/dist/setup/setup.hs:43:50:
error:
• Couldn't match type
‘Distribution.Types.UnqualComponentName.UnqualComponentName’
with ‘[Char]’
Expected type: FilePath
Actual type: Distribution.Types.UnqualComponentName.UnqualComponentName
• In the first argument of ‘(<.>)’, namely ‘exe’
In the second argument of ‘(</>)’, namely ‘exe <.> "exe"’
In the second argument of ‘(</>)’, namely ‘exe </> exe <.> "exe"’
|
43 | else copyFile (builddir </> exe </> exe <.> "exe")
| ^^^

/var/folders/q3/3b4cr3cn4hg8d5bj62pdk16m0000gn/T/cabal-tmp-51525/haste-compiler-0.4.4.4/dist/setup/setup.hs:44:50:
error:
• Couldn't match type
‘Distribution.Types.UnqualComponentName.UnqualComponentName’
with ‘[Char]’
Expected type: FilePath
Actual type: Distribution.Types.UnqualComponentName.UnqualComponentName
• In the first argument of ‘(<.>)’, namely ‘exe’
In the second argument of ‘(</>)’, namely ‘exe <.> "exe"’
In the second argument of ‘(</>)’, namely ‘"bin" </> exe <.> "exe"’
|
44 | (outdir </> "bin" </> exe <.> "exe")
| ^^^

/var/folders/q3/3b4cr3cn4hg8d5bj62pdk16m0000gn/T/cabal-tmp-51525/haste-compiler-0.4.4.4/dist/setup/setup.hs:53:16:
error:
• Data constructor not in scope: FlagName :: String -> FlagName
• Perhaps you meant one of these:
variable ‘flagName’ (imported from Distribution.PackageDescription),
variable ‘unFlagName’ (imported from Distribution.PackageDescription),
variable ‘mkFlagName’ (imported from Distribution.PackageDescription)
|
53 | case lookup (FlagName fn) (configConfigurationsFlags (configFlags lbi))
of
| ^^^^^^^^
)

`

**Comment by b-mehta** [comment]
Also having this issue, and none of the other installation methods are working for me either: 
`stack install` from source gives 

`Unable to find installation URLs for OS key: macosx-nopie`

and `cabal install` gives

`unknown package: bin-package-db (dependency of haste-compiler)`

and there is no pre-built package available for OSX.

**Comment by Huxpro** [comment]
Same problem

**Comment by ghost** [comment]
still not fixed

apparently nobody cares about this project

**Comment by Experiment5X** [comment]
Please fix, this seems like a really cool project

**Comment by WolframKahl** [comment]
It is a really cool project.

> Fresh install of haskell platform 8.2.2

But it only works with GHC-7.10.3.

Please don't even try to install Haste with GHC-8.
