### ISSUE TITLE
Haste 0.2.4 from hackage does not compile with cabal 1.17

### ISSUE THREAD

**Issue by nh2** [valderman/haste-compiler#86]
```
Downloading haste-compiler-0.2.4...
[1 of 1] Compiling Main             ( /tmp/haste-compiler-0.2.4-5471/haste-compiler-0.2.4/Setup.hs, /tmp/haste-compiler-0.2.4-5471/haste-compiler-0.2.4/dist/setup/Main.o )

/tmp/haste-compiler-0.2.4-5471/haste-compiler-0.2.4/Setup.hs:14:31:
    Not in scope: `executableConfigs'
Failed to install haste-compiler-0.2.4
```

**EDIT:** Ah, I just realized that's because I'm using the development version of Cabal. Looks like an `#if` is needed :/
